package sqlServer

type InfoCustomers struct {
	IDClient                        *string `json:"id_client"`
	TokenID                         *string `json:"token_id"`
	Nom                             *string `json:"nom"`
	Civ1                            *string `json:"civ1"`
	Prenom1                         *string `json:"prenom1"`
	DateNaissance1                  *string `json:"date_naissance1"`
	AnneeNaissanceScore1            *int    `json:"annee_naissance_score1"`
	Email1                          *string `json:"email1"`
	OptinEmail1                     *bool   `json:"optin_email1"`
	OptinFidEmail1                  *bool   `json:"optin_fid_email1"`
	Civ2                            *string `json:"civ2"`
	Prenom2                         *string `json:"prenom2"`
	DateNaissance2                  *string `json:"date_naissance2"`
	AnneeNaissanceScore2            *int    `json:"annee_naissance_score2"`
	Email2                          *string `json:"email2"`
	OptinEmail2                     *bool   `json:"optin_email2"`
	OptinFidEmail2                  *bool   `json:"optin_fid_email2"`
	Adresse2                        *string `json:"adresse2"`
	Adresse3                        *string `json:"adresse3"`
	Adresse4                        *string `json:"adresse4"`
	Adresse5                        *string `json:"adresse5"`
	CodePostal                      *string `json:"code_postal"`
	Ville                           *string `json:"ville"`
	CodeInsee                       *string `json:"code_insee"`
	CodeCanton                      *string `json:"code_canton"`
	TopFrance                       *string `json:"top_france"`
	TopCE                           *string `json:"top_ce"`
	TelFixe                         *string `json:"tel_fixe"`
	BloctelTelFixe                  *bool   `json:"bloctel_tel_fixe"`
	DemarchageTelFixe               *bool   `json:"demarchage_tel_fixe"`
	TelMobile                       *string `json:"tel_mobile"`
	BloctelTelMobile                *bool   `json:"bloctel_tel_mobile"`
	DemarchageTelMobile             *bool   `json:"demarchage_tel_mobile"`
	OptinSMS                        *bool   `json:"optin_sms"`
	CodeCEDecla                     *string `json:"code_ce_decla"`
	CodeCEGeoVente                  *string `json:"code_ce_geo_vente"`
	CodeCEGeoSav                    *string `json:"code_ce_geo_sav"`
	Proprietaire                    *string `json:"proprietaire"`
	MomentJoindre                   *int    `json:"moment_joindre"`
	LibelleMomentJoindre            *string `json:"libelle_moment_joindre"`
	IntentionChangementVehicule     *string `json:"intention_changement_vehicule"`
	DateIntentionChangementVehicule *string `json:"date_intention_changement_vehicule"`
	NbEnf                           *int    `json:"Nb_Enf"`
	SexeEnfant1                     *string `json:"sexe_enfant1"`
	PrenomEnfant1                   *string `json:"prenom_enfant1"`
	DateNaissanceEnfant1            *string `json:"datenaissance_enfant1"`
	SexeEnfant2                     *string `json:"sexe_enfant2"`
	PrenomEnfant2                   *string `json:"prenom_enfant2"`
	DateNaissanceEnfant2            *string `json:"datenaissance_enfant2"`
	SexeEnfant3                     *string `json:"sexe_enfant3"`
	PrenomEnfant3                   *string `json:"prenom_enfant3"`
	DateNaissanceEnfant3            *string `json:"datenaissance_enfant3"`
	SexeEnfant4                     *string `json:"sexe_enfant4"`
	PrenomEnfant4                   *string `json:"prenom_enfant4"`
	DateNaissanceEnfant4            *string `json:"datenaissance_enfant4"`
	ComplementRaisonSociale         *string `json:"complement_raison_sociale"`
	CodeSiren                       *string `json:"code_siren"`
	CodeSiret                       *string `json:"code_siret"`
	CodeApe                         *string `json:"code_ape"`
	LibelleApe                      *string `json:"libelle_ape"`
	RubriqueProfessionnel           *string `json:"rubrique_professionnel"`
	NbVehiculeFlotte                *int    `json:"nb_vehicule_flotte"`
	TypeModeleFlotte                *string `json:"type_modele_flotte"`
	TrancheEffectifSociete          *int    `json:"tranche_effectif_societe"`
	LibelleTrancheEffectifSociete   *string `json:"libelle_tranche_effectif_societe"`
	MySuzukiPreinscription          *string `json:"mysuzuki_preinscription"`
	MySuzukiInscription             *string `json:"mysuzuki_inscription"`
	MySuzukiDesinscription          *string `json:"mysuzuki_desinscription"`
	MySuzukiDerniereConnexion       *string `json:"mysuzuki_derniere_connexion"`
	MySuzukiInscriptionPrecedente   *string `json:"mysuzuki_inscription_precedente"`
	TypeClient                      *string `json:"type_client"`
}
